// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChE3Ef2ENaf8vQSNx7YKrQVlrw6cQsGhY',
    appId: '1:160040049160:web:f27b382c8943deb0c30fbd',
    messagingSenderId: '160040049160',
    projectId: 'grocery-mashinin',
    authDomain: 'grocery-mashinin.firebaseapp.com',
    storageBucket: 'grocery-mashinin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdo70uQWrppoG1v7wvUXO6dquQAAqpDU',
    appId: '1:160040049160:android:c2bc6ff8b49122d8c30fbd',
    messagingSenderId: '160040049160',
    projectId: 'grocery-mashinin',
    storageBucket: 'grocery-mashinin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcLhceAX5V6UClMXQZNyONaItMbMuL7Ok',
    appId: '1:160040049160:ios:c58f8263b0bd3e93c30fbd',
    messagingSenderId: '160040049160',
    projectId: 'grocery-mashinin',
    storageBucket: 'grocery-mashinin.appspot.com',
    androidClientId: '160040049160-0binaevt33hq6do0uukm5lqt9obmvv25.apps.googleusercontent.com',
    iosClientId: '160040049160-n7j4mioj6l3etugrhad7p9btkmedim9n.apps.googleusercontent.com',
    iosBundleId: 'com.sinelnikov.grocery',
  );

}